# Railway.app Configuration
# This tells Railway exactly how to build and deploy your app

[build]
builder = "DOCKERFILE"
dockerfilePath = "config/Dockerfile"

[deploy]
startCommand = "java -jar app.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
